var searchData=
[
  ['each_20of_20them_20this_20seems_20pretty_20tedious_0',['I have several test suites which share the same test fixture logic, do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md97',1,'']]],
  ['effects_1',['Effects',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#MockingSideEffects',1,'Mocking Side Effects'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md245',1,'Side Effects']]],
  ['effects_2',['Matchers must have no side-effects',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#PureMatchers',1,'']]],
  ['elapsed_20time_3',['Suppressing the Elapsed Time',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md72',1,'']]],
  ['elapsed_5ftime_20testresult_3a_3aelapsed_5ftime_4',['elapsed_time {TestResult::elapsed_time}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md371',1,'']]],
  ['elapsed_5ftime_20testsuite_3a_3aelapsed_5ftime_5',['elapsed_time {TestSuite::elapsed_time}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md299',1,'']]],
  ['elapsed_5ftime_20unittest_3a_3aelapsed_5ftime_6',['elapsed_time {UnitTest::elapsed_time}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md331',1,'']]],
  ['element_7',['Element',['../class_ti_xml_handle.html#ac56814c76757eecc5bd951d3ed710dd2',1,'TiXmlHandle']]],
  ['elemfromlist_8',['ElemFromList',['../structtesting_1_1internal_1_1_elem_from_list.html',1,'testing::internal']]],
  ['elemfromlist_3c_20i_2c_20args_2e_2e_2e_20_3e_9',['ElemFromList&lt; I, Args... &gt;',['../structtesting_1_1internal_1_1_elem_from_list.html',1,'testing::internal']]],
  ['elemfromlist_3c_20i_2c_20t_2e_2e_2e_20_3e_10',['ElemFromList&lt; I, T... &gt;',['../structtesting_1_1internal_1_1_elem_from_list.html',1,'testing::internal']]],
  ['elemfromlistimpl_11',['ElemFromListImpl',['../structtesting_1_1internal_1_1_elem_from_list_impl.html',1,'testing::internal']]],
  ['elemfromlistimpl_3c_20indexsequence_3c_20i_2e_2e_2e_20_3e_20_3e_12',['ElemFromListImpl&lt; IndexSequence&lt; I... &gt; &gt;',['../structtesting_1_1internal_1_1_elem_from_list_impl_3_01_index_sequence_3_01_i_8_8_8_01_4_01_4.html',1,'testing::internal']]],
  ['emacs_13',['Running Tests in Emacs',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md166',1,'']]],
  ['emptybasenameparaminst_14',['EmptyBasenameParamInst',['../class_empty_basename_param_inst.html',1,'']]],
  ['emptytesteventlistener_15',['EmptyTestEventListener',['../class_empty_test_event_listener.html',1,'EmptyTestEventListener'],['../classtesting_1_1_empty_test_event_listener.html',1,'testing::EmptyTestEventListener'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#EmptyTestEventListener',1,'EmptyTestEventListener']]],
  ['enableif_16',['EnableIf',['../structtesting_1_1internal_1_1_enable_if.html',1,'testing::internal']]],
  ['enableif_3c_20true_20_3e_17',['EnableIf&lt; true &gt;',['../structtesting_1_1internal_1_1_enable_if_3_01true_01_4.html',1,'testing::internal']]],
  ['enabling_20disabled_20tests_18',['Temporarily Enabling Disabled Tests',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md65',1,'']]],
  ['encodestring_19',['EncodeString',['../class_ti_xml_base.html#a32ed202562b58de64c7d799ca3c9db98',1,'TiXmlBase']]],
  ['encoding_20',['Encoding',['../class_ti_xml_declaration.html#a52a6e73b714d3ea590e022178e54b9d3',1,'TiXmlDeclaration']]],
  ['encountered_20default_20action_20taken_20should_20i_20panic_21',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md195',1,'']]],
  ['entire_20test_20suite_20deathtest_20when_20it_20contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_22',['But I don&apos;t like calling my entire test suite *DeathTest when it contains both death tests and non-death tests. What do I do?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md104',1,'']]],
  ['entire_20test_20suite_20instead_20of_20individual_20tests_20to_20be_20named_20deathtest_20when_20it_20uses_20assert_5fdeath_23',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named *DeathTest when it uses ASSERT_DEATH?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md103',1,'']]],
  ['environment_24',['Environment',['../class_environment.html',1,'Environment'],['../classtesting_1_1_environment.html',1,'testing::Environment'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#Environment',1,'Environment']]],
  ['environment_3a_3asetup_25',['SetUp {Environment::SetUp}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md275',1,'']]],
  ['environment_3a_3ateardown_26',['TearDown {Environment::TearDown}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md276',1,'']]],
  ['environmentinvocationcatcher_27',['EnvironmentInvocationCatcher',['../class_environment_invocation_catcher.html',1,'EnvironmentInvocationCatcher'],['../classtesting_1_1internal_1_1_environment_invocation_catcher.html',1,'testing::internal::EnvironmentInvocationCatcher']]],
  ['eqhelper_28',['EqHelper',['../classtesting_1_1internal_1_1_eq_helper.html',1,'testing::internal']]],
  ['eqhelper_3c_20true_20_3e_29',['EqHelper&lt; true &gt;',['../classtesting_1_1internal_1_1_eq_helper_3_01true_01_4.html',1,'testing::internal']]],
  ['error_30',['Error',['../class_ti_xml_document.html#a348e68faad4a3498f413c51ee9bc321a',1,'TiXmlDocument']]],
  ['error_20messages_31',['Predicate Assertions for Better Error Messages',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md15',1,'']]],
  ['error_20no_20matching_20function_20for_20call_20to_20footest_3a_3afootest_20why_32',['I have a fixture class &lt;span class=&quot;tt&quot;&gt;FooTest&lt;/span&gt;, but &lt;span class=&quot;tt&quot;&gt;TEST_F(FooTest, Bar)&lt;/span&gt; gives me error &lt;span class=&quot;tt&quot;&gt;&quot;no matching function for call to `FooTestFooTest()&apos;&quot;&lt;/span&gt;. Why?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md101',1,'']]],
  ['errorcol_33',['ErrorCol',['../class_ti_xml_document.html#adea69de889449a2587afb8ee043f43f5',1,'TiXmlDocument']]],
  ['errordesc_34',['ErrorDesc',['../class_ti_xml_document.html#a03d596f13b24ebae712b2c42b019a5ab',1,'TiXmlDocument']]],
  ['errorid_35',['ErrorId',['../class_ti_xml_document.html#abd928b49a646c8ed53e0453c555d96a2',1,'TiXmlDocument']]],
  ['errorrow_36',['ErrorRow',['../class_ti_xml_document.html#a062e5257128a7da31b0b2e38cd524600',1,'TiXmlDocument']]],
  ['errors_20about_20invalid_20proto_20descriptors_20when_20using_20protocolmessageequals_20help_37',['I got some run-time errors about invalid proto descriptors when using &lt;span class=&quot;tt&quot;&gt;ProtocolMessageEquals&lt;/span&gt;. Help!',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md86',1,'']]],
  ['errors_20in_20opt_20mode_20is_20this_20a_20googletest_20bug_38',['EXPECT_EQ(htonl(blah), blah_blah) generates weird compiler errors in opt mode. Is this a GoogleTest bug?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md88',1,'']]],
  ['even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_39',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['event_20listeners_40',['Event Listeners',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md56',1,'Defining Event Listeners'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md57',1,'Using Event Listeners']]],
  ['eventrecordinglistener_41',['EventRecordingListener',['../class_event_recording_listener.html',1,'EventRecordingListener'],['../classtesting_1_1internal_1_1_event_recording_listener.html',1,'testing::internal::EventRecordingListener']]],
  ['eventrecordinglistener2_42',['EventRecordingListener2',['../class_event_recording_listener2.html',1,'EventRecordingListener2'],['../classtesting_1_1internal_1_1_event_recording_listener2.html',1,'testing::internal::EventRecordingListener2']]],
  ['events_43',['Extending googletest by Handling Test Events',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md55',1,'']]],
  ['exactly_44',['Matching Argument Values Exactly',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md130',1,'']]],
  ['exception_45',['Asserting on Subroutines with an exception',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md39',1,'']]],
  ['exception_20assertions_46',['Exception Assertions',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md14',1,'Exception Assertions'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#exceptions',1,'Exception Assertions']]],
  ['exceptions_47',['Disabling Catching Test-Thrown Exceptions',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md79',1,'']]],
  ['excessivearg_48',['ExcessiveArg',['../structtesting_1_1internal_1_1_excessive_arg.html',1,'testing::internal']]],
  ['execution_49',['Skipping test execution',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md26',1,'']]],
  ['execution_20upon_20first_20failure_50',['Stop test execution upon first failure',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md63',1,'']]],
  ['existing_20boolean_20function_51',['Using an Existing Boolean Function',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md16',1,'']]],
  ['existing_20cmake_20project_52',['Incorporating Into An Existing CMake Project',['../dir_df5ccadbaeaec269c116ba4c8accecee.html#autotoc_md397',1,'']]],
  ['existing_20code_53',['Simplifying the Interface without Breaking Existing Code',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#SimplerInterfaces',1,'']]],
  ['exit_54',['Detecting Test Premature Exit',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md77',1,'']]],
  ['expect_55',['Expect',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#UseOnCall',1,'Knowing When to Expect'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md210',1,'Matchers: What Arguments Do We Expect?']]],
  ['expect_5fany_5fthrow_56',['EXPECT_ANY_THROW',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_ANY_THROW',1,'']]],
  ['expect_5fcall_57',['EXPECT_CALL',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#EXPECT_CALL',1,'']]],
  ['expect_5fcall_20after_58',['After {EXPECT_CALL.After}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md266',1,'']]],
  ['expect_5fcall_20insequence_59',['InSequence {EXPECT_CALL.InSequence}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md265',1,'']]],
  ['expect_5fcall_20is_20called_20even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_60',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['expect_5fcall_20retiresonsaturation_61',['RetiresOnSaturation {EXPECT_CALL.RetiresOnSaturation}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md269',1,'']]],
  ['expect_5fcall_20times_62',['Times {EXPECT_CALL.Times}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md264',1,'']]],
  ['expect_5fcall_20willonce_63',['WillOnce {EXPECT_CALL.WillOnce}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md267',1,'']]],
  ['expect_5fcall_20willrepeatedly_64',['WillRepeatedly {EXPECT_CALL.WillRepeatedly}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md268',1,'']]],
  ['expect_5fcall_20with_65',['With {EXPECT_CALL.With}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md263',1,'']]],
  ['expect_5fdeath_66',['EXPECT_DEATH',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_DEATH',1,'']]],
  ['expect_5fdeath_5fif_5fsupported_67',['EXPECT_DEATH_IF_SUPPORTED',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_DEATH_IF_SUPPORTED',1,'']]],
  ['expect_5fdebug_5fdeath_68',['EXPECT_DEBUG_DEATH',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_DEBUG_DEATH',1,'']]],
  ['expect_5fdouble_5feq_69',['EXPECT_DOUBLE_EQ',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_DOUBLE_EQ',1,'']]],
  ['expect_5feq_70',['EXPECT_EQ',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_EQ',1,'']]],
  ['expect_5feq_20htonl_20blah_20blah_5fblah_20generates_20weird_20compiler_20errors_20in_20opt_20mode_20is_20this_20a_20googletest_20bug_71',['EXPECT_EQ(htonl(blah), blah_blah) generates weird compiler errors in opt mode. Is this a GoogleTest bug?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md88',1,'']]],
  ['expect_5feq_20null_20ptr_20and_20assert_5feq_20null_20ptr_20but_20not_20expect_5fne_20null_20ptr_20and_20assert_5fne_20null_20ptr_72',['Why does GoogleTest support &lt;span class=&quot;tt&quot;&gt;EXPECT_EQ(NULL, ptr)&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;ASSERT_EQ(NULL, ptr)&lt;/span&gt; but not &lt;span class=&quot;tt&quot;&gt;EXPECT_NE(NULL, ptr)&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;ASSERT_NE(NULL, ptr)&lt;/span&gt;?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md84',1,'']]],
  ['expect_5fexit_73',['EXPECT_EXIT',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_EXIT',1,'']]],
  ['expect_5ffalse_74',['EXPECT_FALSE',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_FALSE',1,'']]],
  ['expect_5ffloat_5feq_75',['EXPECT_FLOAT_EQ',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_FLOAT_EQ',1,'']]],
  ['expect_5fge_76',['EXPECT_GE',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_GE',1,'']]],
  ['expect_5fgt_77',['EXPECT_GT',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_GT',1,'']]],
  ['expect_5fhresult_5ffailed_78',['EXPECT_HRESULT_FAILED',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_HRESULT_FAILED',1,'']]],
  ['expect_5fhresult_5fsucceeded_79',['EXPECT_HRESULT_SUCCEEDED',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_HRESULT_SUCCEEDED',1,'']]],
  ['expect_5fle_80',['EXPECT_LE',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_LE',1,'']]],
  ['expect_5flt_81',['EXPECT_LT',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_LT',1,'']]],
  ['expect_5fne_82',['EXPECT_NE',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_NE',1,'']]],
  ['expect_5fne_20null_20ptr_20and_20assert_5fne_20null_20ptr_83',['Why does GoogleTest support &lt;span class=&quot;tt&quot;&gt;EXPECT_EQ(NULL, ptr)&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;ASSERT_EQ(NULL, ptr)&lt;/span&gt; but not &lt;span class=&quot;tt&quot;&gt;EXPECT_NE(NULL, ptr)&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;ASSERT_NE(NULL, ptr)&lt;/span&gt;?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md84',1,'']]],
  ['expect_5fnear_84',['EXPECT_NEAR',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_NEAR',1,'']]],
  ['expect_5fno_5fthrow_85',['EXPECT_NO_THROW',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_NO_THROW',1,'']]],
  ['expect_5fpred_86',['EXPECT_PRED*',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_PRED',1,'']]],
  ['expect_5fpred_5fformat_87',['EXPECT_PRED_FORMAT*',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_PRED_FORMAT',1,'']]],
  ['expect_5fstrcaseeq_88',['EXPECT_STRCASEEQ',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_STRCASEEQ',1,'']]],
  ['expect_5fstrcasene_89',['EXPECT_STRCASENE',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_STRCASENE',1,'']]],
  ['expect_5fstreq_90',['EXPECT_STREQ',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_STREQ',1,'']]],
  ['expect_5fstrne_91',['EXPECT_STRNE',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_STRNE',1,'']]],
  ['expect_5fthat_92',['EXPECT_THAT',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_THAT',1,'']]],
  ['expect_5fthrow_93',['EXPECT_THROW',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_THROW',1,'']]],
  ['expect_5ftrue_94',['EXPECT_TRUE',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#EXPECT_TRUE',1,'']]],
  ['expectation_95',['Expectation',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#Expectation',1,'']]],
  ['expectation_20is_20not_20satisfied_20isn_20t_20this_20redundant_96',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['expectation_20order_97',['Expectation Order',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#autotoc_md114',1,'']]],
  ['expectation_20retires_98',['Controlling When an Expectation Retires',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md145',1,'']]],
  ['expectations_99',['Expectations',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#ExpectCall',1,'Setting Expectations'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md142',1,'Setting Expectations'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md208',1,'Setting Expectations'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#MultiExpectations',1,'Using Multiple Expectations']]],
  ['expectations_20are_20not_20satisfied_20what_20should_20i_20do_100',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md184',1,'']]],
  ['expectations_20are_20sticky_20unless_20said_20otherwise_101',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['expectations_20awkward_20why_20does_20gmock_20do_20that_102',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['expectations_20override_20older_20ones_20rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_103',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['expectationset_104',['ExpectationSet',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#ExpectationSet',1,'']]],
  ['expectcalltest_105',['ExpectCallTest',['../classtesting_1_1gmock__function__mocker__test_1_1_expect_call_test.html',1,'testing::gmock_function_mocker_test']]],
  ['expectfailuretest_106',['ExpectFailureTest',['../class_expect_failure_test.html',1,'']]],
  ['expecting_20ordered_20calls_107',['Expecting Ordered Calls',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#OrderedCalls',1,'']]],
  ['expecting_20partially_20ordered_20calls_108',['Expecting Partially Ordered Calls',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#PartialOrder',1,'']]],
  ['explicit_20success_20and_20failure_109',['Explicit Success and Failure',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md13',1,'Explicit Success and Failure'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#success-failure',1,'Explicit Success and Failure']]],
  ['exporting_20api_20symbols_3a_110',['Exporting API symbols:',['../dir_2bd60d4bfa683c373d0268d1dac4c377.html#autotoc_md391',1,'']]],
  ['expression_20syntax_111',['Regular Expression Syntax',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md31',1,'']]],
  ['extending_20gmock_112',['Extending gMock',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md167',1,'']]],
  ['extending_20googletest_20by_20handling_20test_20events_113',['Extending googletest by Handling Test Events',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md55',1,'']]],
  ['externalgeneratortest_114',['ExternalGeneratorTest',['../class_external_generator_test.html',1,'']]],
  ['externalinstantiationtest_115',['ExternalInstantiationTest',['../class_external_instantiation_test.html',1,'']]],
  ['extra_20info_20as_20actions_116',['Using Functions with Extra Info as Actions',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md152',1,'']]]
];
