var searchData=
[
  ['lambda_20as_20an_20action_0',['Using a Function, Functor, or Lambda as an Action',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md246',1,'']]],
  ['lambda_20callback_20without_20arguments_1',['Invoking a Function/Method/Functor/Lambda/Callback Without Arguments',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md153',1,'']]],
  ['lambdas_20as_20actions_2',['Using Functions/Methods/Functors/Lambdas as Actions',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#FunctionsAsActions',1,'']]],
  ['lastattribute_3',['LastAttribute',['../class_ti_xml_element.html#adb3212c0c62ab98dba77b68d41c3fa9e',1,'TiXmlElement']]],
  ['lastchild_4',['LastChild',['../class_ti_xml_node.html#a418603b3d7a2cf33d146521d96e6af20',1,'TiXmlNode::LastChild()'],['../class_ti_xml_node.html#afe68e2adbf007c58d9348b25c44faa79',1,'TiXmlNode::LastChild(const char *_value)']]],
  ['leak_20messages_20on_20windows_5',['How do I suppress the memory leak messages on Windows?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md107',1,'']]],
  ['legacy_20gmock_20faq_6',['Legacy gMock FAQ',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html',1,'']]],
  ['legacy_20macro_20based_20actions_7',['Legacy macro-based Actions',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md173',1,'']]],
  ['legacy_20macro_20based_20parameterized_20actions_8',['Legacy macro-based parameterized Actions',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md174',1,'']]],
  ['legacy_20matcher_20implementation_9',['Legacy Matcher Implementation',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md171',1,'']]],
  ['legacy_20workarounds_20for_20move_20only_20types_10',['Legacy workarounds for move-only types',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#LegacyMoveOnly',1,'']]],
  ['legacymockb_11',['LegacyMockB',['../classtesting_1_1gmock__function__mocker__test_1_1_legacy_mock_b.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockfoo_12',['LegacyMockFoo',['../classtesting_1_1gmock__function__mocker__test_1_1_legacy_mock_foo.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockmethodsizes0_13',['LegacyMockMethodSizes0',['../structtesting_1_1gmock__function__mocker__test_1_1_legacy_mock_method_sizes0.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockmethodsizes1_14',['LegacyMockMethodSizes1',['../structtesting_1_1gmock__function__mocker__test_1_1_legacy_mock_method_sizes1.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockmethodsizes2_15',['LegacyMockMethodSizes2',['../structtesting_1_1gmock__function__mocker__test_1_1_legacy_mock_method_sizes2.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockmethodsizes3_16',['LegacyMockMethodSizes3',['../structtesting_1_1gmock__function__mocker__test_1_1_legacy_mock_method_sizes3.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockmethodsizes4_17',['LegacyMockMethodSizes4',['../structtesting_1_1gmock__function__mocker__test_1_1_legacy_mock_method_sizes4.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockoverloadedonargnumber_18',['LegacyMockOverloadedOnArgNumber',['../classtesting_1_1gmock__function__mocker__test_1_1_legacy_mock_overloaded_on_arg_number.html',1,'testing::gmock_function_mocker_test']]],
  ['legacymockstack_19',['LegacyMockStack',['../classtesting_1_1gmock__function__mocker__test_1_1_legacy_mock_stack.html',1,'testing::gmock_function_mocker_test']]],
  ['lessbyname_20',['LessByName',['../structtesting_1_1internal_1_1_less_by_name.html',1,'testing::internal']]],
  ['library_20dll_21',['As a Shared Library (DLL)',['../dir_df5ccadbaeaec269c116ba4c8accecee.html#autotoc_md402',1,'']]],
  ['library_20support_20features_22',['Underlying library support features',['../dir_2bd60d4bfa683c373d0268d1dac4c377.html#autotoc_md390',1,'']]],
  ['license_20agreements_23',['Contributor License Agreements',['../md_cmake-build-debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md1',1,'']]],
  ['like_20calling_20my_20entire_20test_20suite_20deathtest_20when_20it_20contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_24',['But I don&apos;t like calling my entire test suite *DeathTest when it contains both death tests and non-death tests. What do I do?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md104',1,'']]],
  ['limitations_25',['Known Limitations',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2primer.html#autotoc_md232',1,'']]],
  ['line_20testinfo_3a_3aline_26',['line {TestInfo::line}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md308',1,'']]],
  ['line_5fnumber_20testpartresult_3a_3aline_5fnumber_27',['line_number {TestPartResult::line_number}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md356',1,'']]],
  ['linebreak_28',['LineBreak',['../class_ti_xml_printer.html#a94969892998ef6a200b7f987b756e823',1,'TiXmlPrinter']]],
  ['linked_5fptr_29',['linked_ptr',['../classtesting_1_1internal_1_1linked__ptr.html',1,'testing::internal']]],
  ['linked_5fptr_5finternal_30',['linked_ptr_internal',['../classtesting_1_1internal_1_1linked__ptr__internal.html',1,'testing::internal']]],
  ['linkendchild_31',['LinkEndChild',['../class_ti_xml_node.html#a1a881212554b759865f6cac79a851d38',1,'TiXmlNode']]],
  ['list_32',['Deprecated List',['../deprecated.html',1,'']]],
  ['listeners_33',['Listeners',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md56',1,'Defining Event Listeners'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md58',1,'Generating Failures in Listeners'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md57',1,'Using Event Listeners']]],
  ['listeners_20unittest_3a_3alisteners_34',['listeners {UnitTest::listeners}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md336',1,'']]],
  ['listenertest_35',['ListenerTest',['../classtesting_1_1internal_1_1_listener_test.html',1,'testing::internal']]],
  ['listing_20test_20names_36',['Listing Test Names',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md61',1,'']]],
  ['live_20at_20head_37',['Live at Head',['../dir_24655302de266b7dee5d60163f030803.html#autotoc_md406',1,'']]],
  ['live_20values_20from_20mock_20methods_38',['Returning Live Values from Mock Methods',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md148',1,'']]],
  ['loadfile_39',['LoadFile',['../class_ti_xml_document.html#a4c852a889c02cf251117fd1d9fe1845f',1,'TiXmlDocument::LoadFile(TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)'],['../class_ti_xml_document.html#a879cdf5e981b8b2d2ef82f2546dd28fb',1,'TiXmlDocument::LoadFile(const char *filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)'],['../class_ti_xml_document.html#a41f6fe7200864d1dca663d230caf8db6',1,'TiXmlDocument::LoadFile(FILE *, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)']]],
  ['loadfile_40',['loadFile',['../class_system_parser.html#a55c283092415deafda87642282130f2a',1,'SystemParser']]],
  ['log_20messages_20in_20a_20death_20test_20s_20child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_41',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md105',1,'']]],
  ['log_20messages_20what_20do_20i_20do_42',['GoogleTest output is buried in a whole bunch of LOG messages. What do I do?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md98',1,'']]],
  ['log_20messages_20when_20the_20death_20test_20succeeds_43',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md105',1,'']]],
  ['logging_20additional_20information_44',['Logging Additional Information',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md42',1,'']]],
  ['logging_3a_45',['Logging:',['../dir_2bd60d4bfa683c373d0268d1dac4c377.html#autotoc_md388',1,'']]],
  ['logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_46',['I have several test suites which share the same test fixture logic, do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md97',1,'']]],
  ['lookupblocker_47',['LookupBlocker',['../structtesting_1_1internal_1_1internal__stream__operator__without__lexical__name__lookup_1_1_lookup_blocker.html',1,'testing::internal::internal_stream_operator_without_lexical_name_lookup']]],
  ['lost_20after_20the_20death_20test_20finishes_20why_48',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md87',1,'']]],
  ['lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_49',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md194',1,'']]]
];
