var searchData=
[
  ['random_0',['Random',['../classtesting_1_1internal_1_1_random.html',1,'testing::internal']]],
  ['random_5fseed_20unittest_3a_3arandom_5fseed_1',['random_seed {UnitTest::random_seed}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md317',1,'']]],
  ['rangegenerator_2',['RangeGenerator',['../classtesting_1_1internal_1_1_range_generator.html',1,'testing::internal']]],
  ['rawbytesprinter_3',['RawBytesPrinter',['../structtesting_1_1internal_1_1_raw_bytes_printer.html',1,'testing::internal']]],
  ['re_4',['RE',['../classtesting_1_1gmock__matchers__test_1_1_r_e.html',1,'testing::gmock_matchers_test::RE'],['../classtesting_1_1internal_1_1_r_e.html',1,'testing::internal::RE']]],
  ['real_20object_5',['Delegating Calls to a Real Object',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md127',1,'']]],
  ['real_20object_20is_20fine_20what_20can_20be_20wrong_6',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md188',1,'']]],
  ['real_20object_20is_20invoked_20instead_20what_20s_20the_20problem_7',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md181',1,'']]],
  ['reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_8',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['recipes_20on_20using_20gmock_9',['Misc Recipes on Using gMock',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md159',1,'']]],
  ['recordproperty_20test_3a_3arecordproperty_10',['RecordProperty {Test::RecordProperty}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md283',1,'']]],
  ['redundant_11',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['reference_12',['Reference',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2actions.html',1,'Actions Reference'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html',1,'Assertions Reference'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2matchers.html',1,'Matchers Reference'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html',1,'Mocking Reference'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html',1,'Testing Reference']]],
  ['references_20from_20mock_20methods_13',['Returning References from Mock Methods',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md147',1,'']]],
  ['references_20to_20some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_14',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md89',1,'']]],
  ['register_5ftyped_5ftest_5fsuite_5fp_15',['REGISTER_TYPED_TEST_SUITE_P',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#REGISTER_TYPED_TEST_SUITE_P',1,'']]],
  ['registering_20tests_20programmatically_16',['Registering tests programmatically',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md53',1,'']]],
  ['registertest_17',['RegisterTest',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#RegisterTest',1,'']]],
  ['regular_20expression_20syntax_18',['Regular Expression Syntax',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md31',1,'']]],
  ['related_20macros_3a_19',['Flag related macros:',['../dir_7592e68e2a6296c1c1340ffa3ec0a43a.html#autotoc_md380',1,'']]],
  ['related_20open_20source_20projects_20',['Related Open Source Projects',['../dir_24655302de266b7dee5d60163f030803.html#autotoc_md415',1,'']]],
  ['relationtosourcecopy_21',['RelationToSourceCopy',['../struct_relation_to_source_copy.html',1,'RelationToSourceCopy'],['../structtesting_1_1internal_1_1_relation_to_source_copy.html',1,'testing::internal::RelationToSourceCopy']]],
  ['relationtosourcereference_22',['RelationToSourceReference',['../struct_relation_to_source_reference.html',1,'RelationToSourceReference'],['../structtesting_1_1gtest__printers__test_1_1_relation_to_source_reference.html',1,'testing::gtest_printers_test::RelationToSourceReference'],['../structtesting_1_1internal_1_1_relation_to_source_reference.html',1,'testing::internal::RelationToSourceReference']]],
  ['release_201_2012_201_23',['Release 1.12.1',['../dir_24655302de266b7dee5d60163f030803.html#autotoc_md408',1,'']]],
  ['release_20testeventlisteners_3a_3arelease_24',['Release {TestEventListeners::Release}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md351',1,'']]],
  ['removeattribute_25',['RemoveAttribute',['../class_ti_xml_element.html#a56979767deca794376b1dfa69a525b2a',1,'TiXmlElement']]],
  ['removechild_26',['RemoveChild',['../class_ti_xml_node.html#ae19d8510efc90596552f4feeac9a8fbf',1,'TiXmlNode']]],
  ['removeconst_27',['RemoveConst',['../structtesting_1_1internal_1_1_remove_const.html',1,'testing::internal']]],
  ['removeconst_3c_20const_20t_20_3e_28',['RemoveConst&lt; const T &gt;',['../structtesting_1_1internal_1_1_remove_const_3_01const_01_t_01_4.html',1,'testing::internal']]],
  ['removeconst_3c_20const_20t_5bn_5d_3e_29',['RemoveConst&lt; const T[N]&gt;',['../structtesting_1_1internal_1_1_remove_const_3_01const_01_t_0f_n_0e_4.html',1,'testing::internal']]],
  ['removeconstfromkey_30',['RemoveConstFromKey',['../structtesting_1_1internal_1_1_remove_const_from_key.html',1,'testing::internal']]],
  ['removeconstfromkey_3c_20std_3a_3apair_3c_20const_20k_2c_20v_20_3e_20_3e_31',['RemoveConstFromKey&lt; std::pair&lt; const K, V &gt; &gt;',['../structtesting_1_1internal_1_1_remove_const_from_key_3_01std_1_1pair_3_01const_01_k_00_01_v_01_4_01_4.html',1,'testing::internal']]],
  ['removelocations_32',['RemoveLocations',['../namespacegmock__output__test.html#a59c40167b074a2ef04aecc79a0273f13',1,'gmock_output_test']]],
  ['removememoryaddresses_33',['RemoveMemoryAddresses',['../namespacegmock__output__test.html#ac16c3c4b4875becf250dd73beb381a82',1,'gmock_output_test']]],
  ['removereference_34',['RemoveReference',['../structtesting_1_1internal_1_1_remove_reference.html',1,'testing::internal']]],
  ['removereference_3c_20t_20_26_20_3e_35',['RemoveReference&lt; T &amp; &gt;',['../structtesting_1_1internal_1_1_remove_reference_3_01_t_01_6_01_4.html',1,'testing::internal']]],
  ['removereportheaderandfooter_36',['RemoveReportHeaderAndFooter',['../namespacegmock__output__test.html#acb06643e5e0d0eb85a3bc067e09e56f9',1,'gmock_output_test']]],
  ['removetestnamesofleakedmocks_37',['RemoveTestNamesOfLeakedMocks',['../namespacegmock__output__test.html#ad0a9e9474fb8cb1729c20bc51222c46e',1,'gmock_output_test']]],
  ['repeating_20the_20tests_38',['Repeating the Tests',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md66',1,'']]],
  ['replacechild_39',['ReplaceChild',['../class_ti_xml_node.html#a543208c2c801c84a213529541e904b9f',1,'TiXmlNode']]],
  ['report_40',['Report',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md75',1,'Generating a JSON Report'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md74',1,'Generating an XML Report']]],
  ['reportable_5fdisabled_5ftest_5fcount_20testsuite_3a_3areportable_5fdisabled_5ftest_5fcount_41',['reportable_disabled_test_count {TestSuite::reportable_disabled_test_count}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md292',1,'']]],
  ['reportable_5fdisabled_5ftest_5fcount_20unittest_3a_3areportable_5fdisabled_5ftest_5fcount_42',['reportable_disabled_test_count {UnitTest::reportable_disabled_test_count}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md325',1,'']]],
  ['reportable_5ftest_5fcount_20testsuite_3a_3areportable_5ftest_5fcount_43',['reportable_test_count {TestSuite::reportable_test_count}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md294',1,'']]],
  ['reportable_5ftest_5fcount_20unittest_3a_3areportable_5ftest_5fcount_44',['reportable_test_count {UnitTest::reportable_test_count}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md327',1,'']]],
  ['reported_45',['Controlling How Failures Are Reported',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md76',1,'']]],
  ['require_20the_20entire_20test_20suite_20instead_20of_20individual_20tests_20to_20be_20named_20deathtest_20when_20it_20uses_20assert_5fdeath_46',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named *DeathTest when it uses ASSERT_DEATH?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md103',1,'']]],
  ['requirements_20for_20contributors_47',['Requirements for Contributors',['../md_cmake-build-debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md7',1,'']]],
  ['requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_48',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md85',1,'']]],
  ['resetting_20a_20mock_49',['Verifying and Resetting a Mock',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#autotoc_md115',1,'']]],
  ['resources_20between_20tests_20in_20the_20same_20test_20suite_50',['Sharing Resources Between Tests in the Same Test Suite',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['restricting_20the_20type_20of_20an_20argument_20or_20parameter_20in_20an_20action_51',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md175',1,'']]],
  ['result_52',['Result',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md155',1,'Ignoring an Action&apos;s Result'],['../structtesting_1_1internal_1_1_function.html',1,'testing::internal::Result&lt; F &gt;']]],
  ['result_20of_20a_20function_20functor_20or_20callback_53',['Matching the Result of a Function, Functor, or Callback',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2matchers.html#autotoc_md257',1,'']]],
  ['result_20testinfo_3a_3aresult_54',['result {TestInfo::result}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md312',1,'']]],
  ['retires_55',['Controlling When an Expectation Retires',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md145',1,'']]],
  ['retiresonsaturation_56',['RetiresOnSaturation {EXPECT_CALL.RetiresOnSaturation}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md269',1,'']]],
  ['retiresonsaturation_20expect_5fcall_20retiresonsaturation_57',['RetiresOnSaturation {EXPECT_CALL.RetiresOnSaturation}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md269',1,'']]],
  ['return_20a_20value_20what_20s_20going_20on_58',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md95',1,'']]],
  ['return_20type_59',['Setting the Default Value for a Return Type',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['return_20type_20specified_20what_20does_20it_20mean_60',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md197',1,'']]],
  ['return_20value_20when_20i_20call_20run_5fall_5ftests_20why_61',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md94',1,'']]],
  ['returnaction_62',['ReturnAction',['../classtesting_1_1internal_1_1_return_action.html',1,'testing::internal']]],
  ['returnaction_3c_20bymovewrapper_3c_20t_20_3e_20_3e_63',['ReturnAction&lt; ByMoveWrapper&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1_return_action_3_01_by_move_wrapper_3_01_t_01_4_01_4.html',1,'testing::internal']]],
  ['returnargaction_64',['ReturnArgAction',['../structtesting_1_1internal_1_1_return_arg_action.html',1,'testing::internal']]],
  ['returning_20a_20value_65',['Returning a Value',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md244',1,'']]],
  ['returning_20live_20values_20from_20mock_20methods_66',['Returning Live Values from Mock Methods',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md148',1,'']]],
  ['returning_20references_20from_20mock_20methods_67',['Returning References from Mock Methods',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md147',1,'']]],
  ['returnnewaction_68',['ReturnNewAction',['../structtesting_1_1internal_1_1_return_new_action.html',1,'testing::internal']]],
  ['returnnullaction_69',['ReturnNullAction',['../classtesting_1_1internal_1_1_return_null_action.html',1,'testing::internal']]],
  ['returnpointeeaction_70',['ReturnPointeeAction',['../structtesting_1_1internal_1_1_return_pointee_action.html',1,'testing::internal']]],
  ['returnrefaction_71',['ReturnRefAction',['../classtesting_1_1internal_1_1_return_ref_action.html',1,'testing::internal']]],
  ['returnrefofcopyaction_72',['ReturnRefOfCopyAction',['../classtesting_1_1internal_1_1_return_ref_of_copy_action.html',1,'testing::internal']]],
  ['returnroundrobinaction_73',['ReturnRoundRobinAction',['../classtesting_1_1internal_1_1_return_round_robin_action.html',1,'testing::internal']]],
  ['returns_20an_20assertionresult_74',['Using a Function That Returns an AssertionResult',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md17',1,'']]],
  ['returnvoidaction_75',['ReturnVoidAction',['../classtesting_1_1internal_1_1_return_void_action.html',1,'testing::internal']]],
  ['room_76',['Room',['../class_room.html',1,'Room'],['../class_room.html#ac3c9fef6420fc0191675c65309a6167e',1,'Room::Room()']]],
  ['rootelement_77',['RootElement',['../class_ti_xml_document.html#ab7d8c7025dd910259f1fea16fc72cda0',1,'TiXmlDocument']]],
  ['routines_78',['Using Assertions in Sub-routines',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md36',1,'']]],
  ['row_79',['Row',['../class_ti_xml_base.html#ad0cacca5d76d156b26511f46080b442e',1,'TiXmlBase']]],
  ['rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_80',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['run_20a_20binary_81',['run a binary',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2quickstart-bazel.html#autotoc_md236',1,'Create and run a binary'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2quickstart-cmake.html#autotoc_md241',1,'Create and run a binary']]],
  ['run_20time_20errors_20about_20invalid_20proto_20descriptors_20when_20using_20protocolmessageequals_20help_82',['I got some run-time errors about invalid proto descriptors when using &lt;span class=&quot;tt&quot;&gt;ProtocolMessageEquals&lt;/span&gt;. Help!',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md86',1,'']]],
  ['run_5fall_5ftests_83',['RUN_ALL_TESTS',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#RUN_ALL_TESTS',1,'']]],
  ['run_5fall_5ftests_20why_84',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md94',1,'']]],
  ['runandverify_85',['RunAndVerify',['../classgoogletest-break-on-failure-unittest_1_1_g_test_break_on_failure_unit_test.html#aa10728830adf68f6c0fd9e8ff9a3e5a2',1,'googletest-break-on-failure-unittest.GTestBreakOnFailureUnitTest.RunAndVerify()'],['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a210d536f4dd4dc5d8ea687747ca8d6d5',1,'googletest-filter-unittest.GTestFilterUnitTest.RunAndVerify()'],['../classgoogletest-list-tests-unittest_1_1_g_test_list_tests_unit_test.html#a181f8f8424ac864380a56f443bd571e7',1,'googletest-list-tests-unittest.GTestListTestsUnitTest.RunAndVerify()'],['../classgoogletest-throw-on-failure-test_1_1_throw_on_failure_test.html#a4438abd96792c91b81e3bae28fc27087',1,'googletest-throw-on-failure-test.ThrowOnFailureTest.RunAndVerify()']]],
  ['runandverifyallowingdisabled_86',['RunAndVerifyAllowingDisabled',['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a8ec218a765232f76b13c81f17c8ee11f',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['runandverifywithsharding_87',['RunAndVerifyWithSharding',['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a8c4225edcc9ca56e44976fa0d7d84d0b',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['running_20a_20subset_20of_20the_20tests_88',['Running a Subset of the Tests',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md62',1,'']]],
  ['running_20in_20a_20test_89',['How can my code detect if it is running in a test?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md108',1,'']]],
  ['running_20test_20programs_3a_20advanced_20options_90',['Running Test Programs: Advanced Options',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md59',1,'']]],
  ['running_20tests_20in_20emacs_91',['Running Tests in Emacs',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md166',1,'']]],
  ['runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_92',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['runtimes_93',['Visual Studio Dynamic vs Static Runtimes',['../dir_df5ccadbaeaec269c116ba4c8accecee.html#autotoc_md398',1,'']]],
  ['runwithflag_94',['RunWithFlag',['../namespacegtest__help__test.html#a5aa27057b0ddd8f10405b613d6d3b057',1,'gtest_help_test']]]
];
