var searchData=
[
  ['gaining_20super_20vision_20into_20mock_20calls_0',['Gaining Super Vision into Mock Calls',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md165',1,'']]],
  ['gcc_20complains_20about_20conflicting_20return_20type_20specified_20what_20does_20it_20mean_1',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md197',1,'']]],
  ['general_20syntax_2',['General Syntax',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md209',1,'']]],
  ['generalized_20assertion_3',['Generalized Assertion',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#generalized',1,'']]],
  ['generatereport_4',['generateReport',['../class_system_output.html#a6d4427ff159954b5f8aa5385b4e106bb',1,'SystemOutput']]],
  ['generates_20weird_20compiler_20errors_20in_20opt_20mode_20is_20this_20a_20googletest_20bug_5',['EXPECT_EQ(htonl(blah), blah_blah) generates weird compiler errors in opt mode. Is this a GoogleTest bug?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md88',1,'']]],
  ['generatetypelist_6',['GenerateTypeList',['../structtesting_1_1internal_1_1_generate_type_list.html',1,'testing::internal']]],
  ['generating_20a_20json_20report_7',['Generating a JSON Report',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md75',1,'']]],
  ['generating_20an_20xml_20report_8',['Generating an XML Report',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md74',1,'']]],
  ['generating_20failures_20in_20listeners_9',['Generating Failures in Listeners',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md58',1,'']]],
  ['generatorevaluationtest_10',['GeneratorEvaluationTest',['../class_generator_evaluation_test.html',1,'']]],
  ['generic_20build_20instructions_11',['Generic Build Instructions',['../dir_df5ccadbaeaec269c116ba4c8accecee.html#autotoc_md393',1,'']]],
  ['generic_20comparison_12',['Generic Comparison',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2matchers.html#autotoc_md253',1,'']]],
  ['get_13',['Get',['../classstd_1_1tr1_1_1gtest__internal_1_1_get.html',1,'std::tr1::gtest_internal']]],
  ['get_20a_20heapcheck_20failure_20when_20using_20a_20mock_20object_20but_20using_20a_20real_20object_20is_20fine_20what_20can_20be_20wrong_14',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md188',1,'']]],
  ['get_3c_200_20_3e_15',['Get&lt; 0 &gt;',['../classstd_1_1tr1_1_1gtest__internal_1_1_get_3_010_01_4.html',1,'std::tr1::gtest_internal']]],
  ['get_3c_201_20_3e_16',['Get&lt; 1 &gt;',['../classstd_1_1tr1_1_1gtest__internal_1_1_get_3_011_01_4.html',1,'std::tr1::gtest_internal']]],
  ['get_3c_202_20_3e_17',['Get&lt; 2 &gt;',['../classstd_1_1tr1_1_1gtest__internal_1_1_get_3_012_01_4.html',1,'std::tr1::gtest_internal']]],
  ['get_3c_203_20_3e_18',['Get&lt; 3 &gt;',['../classstd_1_1tr1_1_1gtest__internal_1_1_get_3_013_01_4.html',1,'std::tr1::gtest_internal']]],
  ['get_3c_204_20_3e_19',['Get&lt; 4 &gt;',['../classstd_1_1tr1_1_1gtest__internal_1_1_get_3_014_01_4.html',1,'std::tr1::gtest_internal']]],
  ['get_3c_205_20_3e_20',['Get&lt; 5 &gt;',['../classstd_1_1tr1_1_1gtest__internal_1_1_get_3_015_01_4.html',1,'std::tr1::gtest_internal']]],
  ['get_3c_206_20_3e_21',['Get&lt; 6 &gt;',['../classstd_1_1tr1_1_1gtest__internal_1_1_get_3_016_01_4.html',1,'std::tr1::gtest_internal']]],
  ['get_3c_207_20_3e_22',['Get&lt; 7 &gt;',['../classstd_1_1tr1_1_1gtest__internal_1_1_get_3_017_01_4.html',1,'std::tr1::gtest_internal']]],
  ['get_3c_208_20_3e_23',['Get&lt; 8 &gt;',['../classstd_1_1tr1_1_1gtest__internal_1_1_get_3_018_01_4.html',1,'std::tr1::gtest_internal']]],
  ['get_3c_209_20_3e_24',['Get&lt; 9 &gt;',['../classstd_1_1tr1_1_1gtest__internal_1_1_get_3_019_01_4.html',1,'std::tr1::gtest_internal']]],
  ['getbuilddir_25',['GetBuildDir',['../namespacegtest__test__utils.html#ae72731bc415a2d3fc3d5bd48f2b390bb',1,'gtest_test_utils']]],
  ['getdocument_26',['GetDocument',['../class_ti_xml_node.html#adcb070acefcbaedaa0673d82e530538b',1,'TiXmlNode']]],
  ['getexitstatus_27',['GetExitStatus',['../namespacegmock__test__utils.html#ac27ecc41752ab1bb57ffabb2817dbef6',1,'gmock_test_utils.GetExitStatus()'],['../namespacegtest__test__utils.html#a368d59803771e4fed35ca647fa2fe7b3',1,'gtest_test_utils.GetExitStatus(exit_code)']]],
  ['getflag_28',['GetFlag',['../namespacegtest__test__utils.html#a18688abdcb598894b4284c9dae37aee3',1,'gtest_test_utils']]],
  ['getinstance_20unittest_3a_3agetinstance_29',['GetInstance {UnitTest::GetInstance}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md313',1,'']]],
  ['getleakytests_30',['GetLeakyTests',['../namespacegmock__output__test.html#a771f708605426dc1bb45c4a9be5aff50',1,'gmock_output_test']]],
  ['getnormalizedcommandoutputandleakytests_31',['GetNormalizedCommandOutputAndLeakyTests',['../namespacegmock__output__test.html#ae1fc1dce5d5cc9a66997127b146e5616',1,'gmock_output_test']]],
  ['getnormalizedoutputandleakytests_32',['GetNormalizedOutputAndLeakyTests',['../namespacegmock__output__test.html#ab651959dfea607ed29d7215488ff8022',1,'gmock_output_test']]],
  ['getshellcommandoutput_33',['GetShellCommandOutput',['../namespacegmock__output__test.html#ac834577ccc464c386e01ca1d940ac470',1,'gmock_output_test']]],
  ['getsourcedir_34',['GetSourceDir',['../namespacegmock__test__utils.html#ae6b4256fed63c744d722ecdf0f217529',1,'gmock_test_utils.GetSourceDir()'],['../namespacegtest__test__utils.html#a421b9a63583bf21c794957a3face367b',1,'gtest_test_utils.GetSourceDir()']]],
  ['gettestexecutablepath_35',['GetTestExecutablePath',['../namespacegmock__test__utils.html#a3965eb0947849f247899f6edff7051f7',1,'gmock_test_utils.GetTestExecutablePath()'],['../namespacegtest__test__utils.html#a239f43ff0e44144cb5a1e14f3453c273',1,'gtest_test_utils.GetTestExecutablePath()']]],
  ['gettestinfo_20testsuite_3a_3agettestinfo_36',['GetTestInfo {TestSuite::GetTestInfo}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md301',1,'']]],
  ['gettestpartresult_20testresult_3a_3agettestpartresult_37',['GetTestPartResult {TestResult::GetTestPartResult}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md373',1,'']]],
  ['gettestproperty_20testresult_3a_3agettestproperty_38',['GetTestProperty {TestResult::GetTestProperty}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md374',1,'']]],
  ['gettestsuite_20unittest_3a_3agettestsuite_39',['GetTestSuite {UnitTest::GetTestSuite}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md334',1,'']]],
  ['gettext_40',['GetText',['../class_ti_xml_element.html#af0f814ecbd43d50d4cdbdf4354d3da39',1,'TiXmlElement']]],
  ['getting_20started_41',['Getting Started',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md202',1,'Getting Started'],['../dir_24655302de266b7dee5d60163f030803.html#autotoc_md411',1,'Getting Started']]],
  ['getting_20the_20current_20test_20s_20name_42',['Getting the Current Test&apos;s Name',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md54',1,'']]],
  ['getuserdata_43',['GetUserData',['../class_ti_xml_base.html#a436b80c865d437835d370a9eada6f9f5',1,'TiXmlBase::GetUserData()'],['../class_ti_xml_base.html#aa44896ae7cc0e9b1007429b150a81d92',1,'TiXmlBase::GetUserData() const']]],
  ['gianttemplate_44',['GiantTemplate',['../structtesting_1_1gmock__more__actions__test_1_1_giant_template.html',1,'testing::gmock_more_actions_test']]],
  ['gives_45',['The compiler complains about &lt;span class=&quot;tt&quot;&gt;no match for &apos;operator&amp;lt;&amp;lt;&apos;&lt;/span&gt; when I use an assertion. What gives?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md106',1,'']]],
  ['gives_20me_20error_20no_20matching_20function_20for_20call_20to_20footest_3a_3afootest_20why_46',['I have a fixture class &lt;span class=&quot;tt&quot;&gt;FooTest&lt;/span&gt;, but &lt;span class=&quot;tt&quot;&gt;TEST_F(FooTest, Bar)&lt;/span&gt; gives me error &lt;span class=&quot;tt&quot;&gt;&quot;no matching function for call to `FooTestFooTest()&apos;&quot;&lt;/span&gt;. Why?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md101',1,'']]],
  ['gives_20me_20warning_20c4301_20or_20c4373_20when_20i_20define_20a_20mock_20method_20with_20a_20const_20parameter_20why_47',['MSVC gives me warning C4301 or C4373 when I define a mock method with a const parameter. Why?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md183',1,'']]],
  ['global_20function_20can_20i_20mock_20it_48',['My code calls a static/global function. Can I mock it?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['global_20set_20up_20and_20tear_20down_49',['Global Set-Up and Tear-Down',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md44',1,'']]],
  ['global_20variables_50',['Why should I prefer test fixtures over global variables?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md99',1,'']]],
  ['gmock_51',['gMock',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md167',1,'Extending gMock'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md159',1,'Misc Recipes on Using gMock'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md179',1,'Useful Mocks Created Using gMock'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md200',1,'What Is gMock?'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md201',1,'Why gMock?']]],
  ['gmock_20and_20threads_52',['Using gMock and Threads',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#UsingThreads',1,'']]],
  ['gmock_20bug_53',['My program crashed and &lt;span class=&quot;tt&quot;&gt;ScopedMockLog&lt;/span&gt; spit out tons of messages. Is it a gMock bug?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['gmock_20cheat_20sheet_54',['gMock Cheat Sheet',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html',1,'']]],
  ['gmock_20cookbook_55',['gMock Cookbook',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html',1,'']]],
  ['gmock_20do_20that_56',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['gmock_20faq_57',['Legacy gMock FAQ',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html',1,'']]],
  ['gmock_20for_20dummies_58',['gMock for Dummies',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__for__dummies.html',1,'']]],
  ['gmock_20framework_59',['Googletest Mocking (gMock) Framework',['../dir_ed45d3f6106031d277dd979af121d650.html#autotoc_md381',1,'']]],
  ['gmock_20how_20to_20print_20your_20values_60',['Teaching gMock How to Print Your Values',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md178',1,'']]],
  ['gmock_20matchers_61',['Asserting Using gMock Matchers',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md21',1,'']]],
  ['gmock_20port_20h_62',['Header &lt;span class=&quot;tt&quot;&gt;gmock-port.h&lt;/span&gt;',['../dir_7592e68e2a6296c1c1340ffa3ec0a43a.html#autotoc_md379',1,'']]],
  ['gmock_20prints_63',['Controlling How Much Information gMock Prints',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md164',1,'']]],
  ['gmock_20prints_20a_20warning_20when_20a_20function_20without_20expect_5fcall_20is_20called_20even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_64',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['gmock_20sucks_65',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['gmock_20tells_20me_20twice_20that_20a_20particular_20expectation_20is_20not_20satisfied_20isn_20t_20this_20redundant_66',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['gmock_20thinks_20my_20expectations_20are_20not_20satisfied_20what_20should_20i_20do_67',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md184',1,'']]],
  ['gmock_5fleak_5ftest_68',['gmock_leak_test',['../namespacegmock__leak__test.html',1,'']]],
  ['gmock_5foutput_5ftest_69',['gmock_output_test',['../namespacegmock__output__test.html',1,'']]],
  ['gmock_5ftest_5futils_70',['gmock_test_utils',['../namespacegmock__test__utils.html',1,'']]],
  ['gmockleaktest_71',['GMockLeakTest',['../classgmock__leak__test_1_1_g_mock_leak_test.html',1,'gmock_leak_test']]],
  ['gmockoutputtest_72',['GMockOutputTest',['../classgmock__output__test_1_1_g_mock_output_test.html',1,'gmock_output_test.GMockOutputTest'],['../class_g_mock_output_test.html',1,'GMockOutputTest']]],
  ['going_20on_73',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md95',1,'']]],
  ['google_20mock_74',['Developing Google Test and Google Mock',['../md_cmake-build-debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md8',1,'']]],
  ['google_20mock_20communities_75',['The Google Test and Google Mock Communities',['../md_cmake-build-debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md4',1,'']]],
  ['google_20mock_20themselves_76',['Testing Google Test and Google Mock Themselves',['../md_cmake-build-debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md9',1,'']]],
  ['google_20s_20c_20test_20framework_77',['Welcome to &lt;b&gt;GoogleTest&lt;/b&gt;, Google&apos;s C++ test framework!',['../dir_24655302de266b7dee5d60163f030803.html#autotoc_md410',1,'']]],
  ['google_20test_20and_20google_20mock_78',['Developing Google Test and Google Mock',['../md_cmake-build-debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md8',1,'']]],
  ['google_20test_20and_20google_20mock_20communities_79',['The Google Test and Google Mock Communities',['../md_cmake-build-debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md4',1,'']]],
  ['google_20test_20and_20google_20mock_20themselves_80',['Testing Google Test and Google Mock Themselves',['../md_cmake-build-debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md9',1,'']]],
  ['googler_81',['Are you a Googler?',['../md_cmake-build-debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md2',1,'']]],
  ['googletest_82',['GoogleTest',['../dir_24655302de266b7dee5d60163f030803.html#autotoc_md404',1,'GoogleTest'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2pkgconfig.html#autotoc_md218',1,'Help! pkg-config can&apos;t find GoogleTest!'],['../dir_df5ccadbaeaec269c116ba4c8accecee.html#autotoc_md400',1,'Tweaking GoogleTest'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2index.html#autotoc_md215',1,'Welcome to GoogleTest!'],['../dir_24655302de266b7dee5d60163f030803.html#autotoc_md414',1,'Who Is Using GoogleTest?']]],
  ['googletest_83',['googletest',['../namespacegoogletest.html',1,'googletest'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2primer.html#autotoc_md225',1,'Introduction: Why googletest?']]],
  ['googletest_20assertions_84',['Using Matchers in googletest Assertions',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md135',1,'']]],
  ['googletest_20bug_85',['EXPECT_EQ(htonl(blah), blah_blah) generates weird compiler errors in opt mode. Is this a GoogleTest bug?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md88',1,'']]],
  ['googletest_20by_20handling_20test_20events_86',['Extending googletest by Handling Test Events',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md55',1,'']]],
  ['googletest_20faq_87',['GoogleTest FAQ',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html',1,'']]],
  ['googletest_20from_20various_20build_20systems_88',['Using GoogleTest from various build systems',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2pkgconfig.html',1,'']]],
  ['googletest_20google_20s_20c_20test_20framework_89',['Welcome to &lt;b&gt;GoogleTest&lt;/b&gt;, Google&apos;s C++ test framework!',['../dir_24655302de266b7dee5d60163f030803.html#autotoc_md410',1,'']]],
  ['googletest_20how_20to_20print_20your_20values_90',['Teaching googletest How to Print Your Values',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md27',1,'']]],
  ['googletest_20mocking_20gmock_20framework_91',['Googletest Mocking (gMock) Framework',['../dir_ed45d3f6106031d277dd979af121d650.html#autotoc_md381',1,'']]],
  ['googletest_20output_20is_20buried_20in_20a_20whole_20bunch_20of_20log_20messages_20what_20do_20i_20do_92',['GoogleTest output is buried in a whole bunch of LOG messages. What do I do?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md98',1,'']]],
  ['googletest_20primer_93',['Googletest Primer',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2primer.html',1,'']]],
  ['googletest_20prints_20the_20log_20messages_20in_20a_20death_20test_20s_20child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_94',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md105',1,'']]],
  ['googletest_20require_20the_20entire_20test_20suite_20instead_20of_20individual_20tests_20to_20be_20named_20deathtest_20when_20it_20uses_20assert_5fdeath_95',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named *DeathTest when it uses ASSERT_DEATH?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md103',1,'']]],
  ['googletest_20samples_96',['Googletest Samples',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2samples.html',1,'']]],
  ['googletest_20support_20expect_5feq_20null_20ptr_20and_20assert_5feq_20null_20ptr_20but_20not_20expect_5fne_20null_20ptr_20and_20assert_5fne_20null_20ptr_97',['Why does GoogleTest support &lt;span class=&quot;tt&quot;&gt;EXPECT_EQ(NULL, ptr)&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;ASSERT_EQ(NULL, ptr)&lt;/span&gt; but not &lt;span class=&quot;tt&quot;&gt;EXPECT_NE(NULL, ptr)&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;ASSERT_NE(NULL, ptr)&lt;/span&gt;?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md84',1,'']]],
  ['googletest_20topics_98',['Advanced googletest Topics',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html',1,'']]],
  ['googletest_20user_20s_20guide_99',['GoogleTest User&apos;s Guide',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2index.html',1,'']]],
  ['googletestfailurereporter_100',['GoogleTestFailureReporter',['../classtesting_1_1internal_1_1_google_test_failure_reporter.html',1,'testing::internal']]],
  ['got_20a_20warning_20uninteresting_20function_20call_20encountered_20default_20action_20taken_20should_20i_20panic_101',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md195',1,'']]],
  ['got_20some_20run_20time_20errors_20about_20invalid_20proto_20descriptors_20when_20using_20protocolmessageequals_20help_102',['I got some run-time errors about invalid proto descriptors when using &lt;span class=&quot;tt&quot;&gt;ProtocolMessageEquals&lt;/span&gt;. Help!',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md86',1,'']]],
  ['greaterthanmatcher_103',['GreaterThanMatcher',['../classtesting_1_1gmock__matchers__test_1_1_greater_than_matcher.html',1,'testing::gmock_matchers_test']]],
  ['gtest_20h_104',['Header &lt;span class=&quot;tt&quot;&gt;gtest.h&lt;/span&gt;',['../dir_2bd60d4bfa683c373d0268d1dac4c377.html#autotoc_md385',1,'']]],
  ['gtest_20port_20h_105',['Header &lt;span class=&quot;tt&quot;&gt;gtest-port.h&lt;/span&gt;',['../dir_2bd60d4bfa683c373d0268d1dac4c377.html#autotoc_md387',1,'']]],
  ['gtest_20printers_20h_106',['Header &lt;span class=&quot;tt&quot;&gt;gtest-printers.h&lt;/span&gt;',['../dir_2bd60d4bfa683c373d0268d1dac4c377.html#autotoc_md392',1,'']]],
  ['gtest_5fallow_5funinstantiated_5fparameterized_5ftest_107',['GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST',1,'']]],
  ['gtest_5fhelp_5ftest_108',['gtest_help_test',['../namespacegtest__help__test.html',1,'']]],
  ['gtest_5fjson_5ftest_5futils_109',['gtest_json_test_utils',['../namespacegtest__json__test__utils.html',1,'']]],
  ['gtest_5flist_5foutput_5funittest_110',['gtest_list_output_unittest',['../namespacegtest__list__output__unittest.html',1,'']]],
  ['gtest_5fskip_111',['GTEST_SKIP',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#GTEST_SKIP',1,'']]],
  ['gtest_5fskip_5fcheck_5foutput_5ftest_112',['gtest_skip_check_output_test',['../namespacegtest__skip__check__output__test.html',1,'']]],
  ['gtest_5fskip_5fenvironment_5fcheck_5foutput_5ftest_113',['gtest_skip_environment_check_output_test',['../namespacegtest__skip__environment__check__output__test.html',1,'']]],
  ['gtest_5ftest_5futils_114',['gtest_test_utils',['../namespacegtest__test__utils.html',1,'']]],
  ['gtest_5ftestbridge_5ftest_115',['gtest_testbridge_test',['../namespacegtest__testbridge__test.html',1,'']]],
  ['gtest_5fxml_5foutfiles_5ftest_116',['gtest_xml_outfiles_test',['../namespacegtest__xml__outfiles__test.html',1,'']]],
  ['gtest_5fxml_5foutput_5funittest_117',['gtest_xml_output_unittest',['../namespacegtest__xml__output__unittest.html',1,'']]],
  ['gtest_5fxml_5ftest_5futils_118',['gtest_xml_test_utils',['../namespacegtest__xml__test__utils.html',1,'']]],
  ['gtestbreakonfailureunittest_119',['GTestBreakOnFailureUnitTest',['../classgoogletest-break-on-failure-unittest_1_1_g_test_break_on_failure_unit_test.html',1,'googletest-break-on-failure-unittest']]],
  ['gtestcolortest_120',['GTestColorTest',['../classgoogletest-color-test_1_1_g_test_color_test.html',1,'googletest-color-test']]],
  ['gtestenvvartest_121',['GTestEnvVarTest',['../classgoogletest-env-var-test_1_1_g_test_env_var_test.html',1,'googletest-env-var-test']]],
  ['gtestfailfastunittest_122',['GTestFailFastUnitTest',['../classgoogletest-failfast-unittest_1_1_g_test_fail_fast_unit_test.html',1,'googletest-failfast-unittest']]],
  ['gtestfilterunittest_123',['GTestFilterUnitTest',['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html',1,'googletest-filter-unittest']]],
  ['gtestflagsaver_124',['GTestFlagSaver',['../class_g_test_flag_saver.html',1,'GTestFlagSaver'],['../classtesting_1_1internal_1_1_g_test_flag_saver.html',1,'testing::internal::GTestFlagSaver']]],
  ['gtestglobalenvironmentunittest_125',['GTestGlobalEnvironmentUnitTest',['../classgoogletest-global-environment-unittest_1_1_g_test_global_environment_unit_test.html',1,'googletest-global-environment-unittest']]],
  ['gtestgreaterthanmatcher_126',['GtestGreaterThanMatcher',['../structtesting_1_1gmock__matchers__test_1_1_gtest_greater_than_matcher.html',1,'testing::gmock_matchers_test']]],
  ['gtesthelptest_127',['GTestHelpTest',['../classgtest__help__test_1_1_g_test_help_test.html',1,'gtest_help_test']]],
  ['gtestjsonoutfilestest_128',['GTestJsonOutFilesTest',['../classgoogletest-json-outfiles-test_1_1_g_test_json_out_files_test.html',1,'googletest-json-outfiles-test']]],
  ['gtestjsonoutputunittest_129',['GTestJsonOutputUnitTest',['../classgoogletest-json-output-unittest_1_1_g_test_json_output_unit_test.html',1,'googletest-json-output-unittest']]],
  ['gtestlisttestsoutputunittest_130',['GTestListTestsOutputUnitTest',['../classgtest__list__output__unittest_1_1_g_test_list_tests_output_unit_test.html',1,'gtest_list_output_unittest']]],
  ['gtestlisttestsunittest_131',['GTestListTestsUnitTest',['../classgoogletest-list-tests-unittest_1_1_g_test_list_tests_unit_test.html',1,'googletest-list-tests-unittest']]],
  ['gtestlog_132',['GTestLog',['../classtesting_1_1internal_1_1_g_test_log.html',1,'testing::internal']]],
  ['gtestmatchertestp_133',['GTestMatcherTestP',['../classtesting_1_1gmock__matchers__test_1_1_g_test_matcher_test_p.html',1,'testing::gmock_matchers_test']]],
  ['gtestmutexlock_134',['GTestMutexLock',['../classtesting_1_1internal_1_1_g_test_mutex_lock.html',1,'testing::internal']]],
  ['gtestnoncopyable_135',['GTestNonCopyable',['../classtesting_1_1internal_1_1_g_test_non_copyable.html',1,'testing::internal']]],
  ['gtestoutputtest_136',['GTestOutputTest',['../classgoogletest-output-test_1_1_g_test_output_test.html',1,'googletest-output-test']]],
  ['gtestparamtestinvalidname1test_137',['GTestParamTestInvalidName1Test',['../classgoogletest-param-test-invalid-name1-test_1_1_g_test_param_test_invalid_name1_test.html',1,'googletest-param-test-invalid-name1-test']]],
  ['gtestparamtestinvalidname2test_138',['GTestParamTestInvalidName2Test',['../classgoogletest-param-test-invalid-name2-test_1_1_g_test_param_test_invalid_name2_test.html',1,'googletest-param-test-invalid-name2-test']]],
  ['gtestsetuptestsuitetest_139',['GTestSetUpTestSuiteTest',['../classgoogletest-setuptestsuite-test_1_1_g_test_set_up_test_suite_test.html',1,'googletest-setuptestsuite-test']]],
  ['gtestshuffleunittest_140',['GTestShuffleUnitTest',['../classgoogletest-shuffle-test_1_1_g_test_shuffle_unit_test.html',1,'googletest-shuffle-test']]],
  ['gtesttestfiltertest_141',['GTestTestFilterTest',['../classgtest__testbridge__test_1_1_g_test_test_filter_test.html',1,'gtest_testbridge_test']]],
  ['gtestuninitializedtest_142',['GTestUninitializedTest',['../classgoogletest-uninitialized-test_1_1_g_test_uninitialized_test.html',1,'googletest-uninitialized-test']]],
  ['gtestxmloutfilestest_143',['GTestXMLOutFilesTest',['../classgtest__xml__outfiles__test_1_1_g_test_x_m_l_out_files_test.html',1,'gtest_xml_outfiles_test']]],
  ['gtestxmloutputunittest_144',['GTestXMLOutputUnitTest',['../classgtest__xml__output__unittest_1_1_g_test_x_m_l_output_unit_test.html',1,'gtest_xml_output_unittest']]],
  ['gtestxmltestcase_145',['GTestXMLTestCase',['../classgtest__xml__test__utils_1_1_g_test_x_m_l_test_case.html',1,'gtest_xml_test_utils']]],
  ['guide_146',['GoogleTest User&apos;s Guide',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2index.html',1,'']]]
];
