var searchData=
[
  ['samesizetupleprefixcomparator_0',['SameSizeTuplePrefixComparator',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_200_2c_200_20_3e_1',['SameSizeTuplePrefixComparator&lt; 0, 0 &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_010_00_010_01_4.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_20k_2c_20k_20_3e_2',['SameSizeTuplePrefixComparator&lt; k, k &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_01k_00_01k_01_4.html',1,'std::tr1::gtest_internal']]],
  ['saveargaction_3',['SaveArgAction',['../structtesting_1_1internal_1_1_save_arg_action.html',1,'testing::internal']]],
  ['saveargpointeeaction_4',['SaveArgPointeeAction',['../structtesting_1_1internal_1_1_save_arg_pointee_action.html',1,'testing::internal']]],
  ['scoped_5fptr_5',['scoped_ptr',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astring_20_3e_6',['scoped_ptr&lt; ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astringstream_20_3e_7',['scoped_ptr&lt; ::std::stringstream &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20_3a_3astd_3a_3astring_20_3e_8',['scoped_ptr&lt; const ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scopedfaketestpartresultreporter_9',['ScopedFakeTestPartResultReporter',['../class_scoped_fake_test_part_result_reporter.html',1,'ScopedFakeTestPartResultReporter'],['../classtesting_1_1_scoped_fake_test_part_result_reporter.html',1,'testing::ScopedFakeTestPartResultReporter']]],
  ['scopedprematureexitfile_10',['ScopedPrematureExitFile',['../classtesting_1_1internal_1_1_scoped_premature_exit_file.html',1,'testing::internal']]],
  ['scopedtrace_11',['ScopedTrace',['../classtesting_1_1internal_1_1_scoped_trace.html',1,'testing::internal::ScopedTrace'],['../classtesting_1_1_scoped_trace.html',1,'testing::ScopedTrace']]],
  ['separateinstancetest_12',['SeparateInstanceTest',['../class_separate_instance_test.html',1,'']]],
  ['sequencetestinglistener_13',['SequenceTestingListener',['../class_sequence_testing_listener.html',1,'']]],
  ['setargrefereeaction_14',['SetArgRefereeAction',['../structtesting_1_1internal_1_1_set_arg_referee_action.html',1,'testing::internal']]],
  ['setargumentpointeeaction_15',['SetArgumentPointeeAction',['../structtesting_1_1internal_1_1_set_argument_pointee_action.html',1,'testing::internal']]],
  ['setarrayargumentaction_16',['SetArrayArgumentAction',['../structtesting_1_1internal_1_1_set_array_argument_action.html',1,'testing::internal']]],
  ['seterrnoandreturnaction_17',['SetErrnoAndReturnAction',['../classtesting_1_1internal_1_1_set_errno_and_return_action.html',1,'testing::internal']]],
  ['setupenvironment_18',['SetupEnvironment',['../class_setup_environment.html',1,'']]],
  ['setupfailtest_19',['SetupFailTest',['../class_setup_fail_test.html',1,'']]],
  ['setuptestcasetest_20',['SetUpTestCaseTest',['../classtesting_1_1_set_up_test_case_test.html',1,'testing']]],
  ['setuptestsuitetest_21',['SetUpTestSuiteTest',['../classtesting_1_1_set_up_test_suite_test.html',1,'testing']]],
  ['singlefailurechecker_22',['SingleFailureChecker',['../classtesting_1_1internal_1_1_single_failure_checker.html',1,'testing::internal']]],
  ['skipentireenvironmenttest_23',['SkipEntireEnvironmentTest',['../classgtest__skip__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_check_output_test.SkipEntireEnvironmentTest'],['../classgtest__skip__environment__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_environment_check_output_test.SkipEntireEnvironmentTest']]],
  ['skippedtest_24',['SkippedTest',['../class_skipped_test.html',1,'']]],
  ['stackinterface_25',['StackInterface',['../classtesting_1_1gmock__function__mocker__test_1_1_stack_interface.html',1,'testing::gmock_function_mocker_test']]],
  ['statefulnamingfunctor_26',['StatefulNamingFunctor',['../struct_stateful_naming_functor.html',1,'']]],
  ['statefulnamingtest_27',['StatefulNamingTest',['../class_stateful_naming_test.html',1,'']]],
  ['staticasserttypeeqhelper_28',['StaticAssertTypeEqHelper',['../structtesting_1_1internal_1_1_static_assert_type_eq_helper.html',1,'testing::internal']]],
  ['staticasserttypeeqhelper_3c_20t_2c_20t_20_3e_29',['StaticAssertTypeEqHelper&lt; T, T &gt;',['../structtesting_1_1internal_1_1_static_assert_type_eq_helper_3_01_t_00_01_t_01_4.html',1,'testing::internal']]],
  ['staticasserttypeeqtesthelper_30',['StaticAssertTypeEqTestHelper',['../class_static_assert_type_eq_test_helper.html',1,'']]],
  ['stlcontainerview_31',['StlContainerView',['../classtesting_1_1internal_1_1_stl_container_view.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20_3a_3astd_3a_3atuple_3c_20elementpointer_2c_20size_20_3e_20_3e_32',['StlContainerView&lt; ::std::tuple&lt; ElementPointer, Size &gt; &gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_1_1std_1_1tuple_3_01_element_pointer_00_01_size_01_4_01_4.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20element_5bn_5d_3e_33',['StlContainerView&lt; Element[N]&gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_element_0f_n_0e_4.html',1,'testing::internal']]],
  ['streamableinglobal_34',['StreamableInGlobal',['../class_streamable_in_global.html',1,'']]],
  ['streamableinlocal_35',['StreamableInLocal',['../structfoo_1_1_streamable_in_local.html',1,'foo']]],
  ['streamabletemplateinfoo_36',['StreamableTemplateInFoo',['../classfoo_1_1_streamable_template_in_foo.html',1,'foo']]],
  ['streamprinter_37',['StreamPrinter',['../structtesting_1_1internal_1_1internal__stream__operator__without__lexical__name__lookup_1_1_stream_printer.html',1,'testing::internal::internal_stream_operator_without_lexical_name_lookup']]],
  ['strictmock_38',['StrictMock',['../classtesting_1_1gmock__nice__strict__test_1_1_strict_mock.html',1,'testing::gmock_nice_strict_test::StrictMock&lt; MockClass &gt;'],['../classtesting_1_1_strict_mock.html',1,'testing::StrictMock&lt; MockClass &gt;']]],
  ['strictmockimpl_39',['StrictMockImpl',['../classtesting_1_1internal_1_1_strict_mock_impl.html',1,'testing::internal']]],
  ['strictmockimpl_3c_20mockclass_20_3e_40',['StrictMockImpl&lt; MockClass &gt;',['../classtesting_1_1internal_1_1_strict_mock_impl.html',1,'testing::internal']]],
  ['string_41',['String',['../class_string.html',1,'String'],['../classtesting_1_1internal_1_1_string.html',1,'testing::internal::String']]],
  ['subprocess_42',['Subprocess',['../classgtest__test__utils_1_1_subprocess.html',1,'gtest_test_utils']]],
  ['successfultest_43',['SuccessfulTest',['../class_successful_test.html',1,'']]],
  ['suiteapiresolver_44',['SuiteApiResolver',['../structtesting_1_1internal_1_1_suite_api_resolver.html',1,'testing::internal']]],
  ['sumof5functor_45',['SumOf5Functor',['../structtesting_1_1gmock__more__actions__test_1_1_sum_of5_functor.html',1,'testing::gmock_more_actions_test']]],
  ['sumof6functor_46',['SumOf6Functor',['../structtesting_1_1gmock__more__actions__test_1_1_sum_of6_functor.html',1,'testing::gmock_more_actions_test']]],
  ['systemoutput_47',['SystemOutput',['../class_system_output.html',1,'']]],
  ['systemparser_48',['SystemParser',['../class_system_parser.html',1,'']]]
];
