var searchData=
[
  ['validating_20a_20member_20of_20an_20object_0',['Validating a Member of an Object',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md138',1,'']]],
  ['validating_20the_20value_20pointed_20to_20by_20a_20pointer_20argument_1',['Validating the Value Pointed to by a Pointer Argument',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md139',1,'']]],
  ['value_2',['Returning a Value',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md244',1,'']]],
  ['value_3',['value',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#value',1,'']]],
  ['value_20for_20a_20return_20type_4',['Setting the Default Value for a Return Type',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['value_20not_20ignored_20as_20it_20ought_20to_20be_20what_20does_20this_20mean_5',['My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md91',1,'']]],
  ['value_20parameterized_20abstract_20tests_6',['Creating Value-Parameterized Abstract Tests',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md47',1,'']]],
  ['value_20parameterized_20test_20parameters_7',['Specifying Names for Value-Parameterized Test Parameters',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md48',1,'']]],
  ['value_20parameterized_20tests_8',['Value Parameterized Tests',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md46',1,'How to Write Value-Parameterized Tests'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md45',1,'Value-Parameterized Tests']]],
  ['value_20parameterized_20tests_9',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md85',1,'']]],
  ['value_20pointed_20to_20by_20a_20pointer_20argument_10',['Validating the Value Pointed to by a Pointer Argument',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md139',1,'']]],
  ['value_20what_20s_20going_20on_11',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md95',1,'']]],
  ['value_20when_20i_20call_20run_5fall_5ftests_20why_12',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md94',1,'']]],
  ['value_5fparam_20testinfo_3a_3avalue_5fparam_13',['value_param {TestInfo::value_param}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md306',1,'']]],
  ['values_14',['Values',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md178',1,'Teaching gMock How to Print Your Values'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md27',1,'Teaching googletest How to Print Your Values']]],
  ['values_20exactly_15',['Matching Argument Values Exactly',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md130',1,'']]],
  ['values_20from_20mock_20methods_16',['Returning Live Values from Mock Methods',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md148',1,'']]],
  ['variables_17',['Why should I prefer test fixtures over global variables?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md99',1,'']]],
  ['variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_18',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md89',1,'']]],
  ['variadic_20function_19',['Can I mock a variadic function?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md182',1,'']]],
  ['various_20build_20systems_20',['Using GoogleTest from various build systems',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2pkgconfig.html',1,'']]],
  ['verification_21',['Forcing a Verification',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md162',1,'']]],
  ['verifying_20and_20resetting_20a_20mock_22',['Verifying and Resetting a Mock',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#autotoc_md115',1,'']]],
  ['verifying_20complex_20arguments_23',['Verifying Complex Arguments',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#SaveArgVerify',1,'']]],
  ['version_24',['C++ Standard Version',['../dir_df5ccadbaeaec269c116ba4c8accecee.html#autotoc_md399',1,'']]],
  ['virtual_20methods_25',['Mocking Non-virtual Methods',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#MockingNonVirtualMethods',1,'']]],
  ['vision_20into_20mock_20calls_26',['Gaining Super Vision into Mock Calls',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md165',1,'']]],
  ['visual_20c_20runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_27',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['visual_20studio_20dynamic_20vs_20static_20runtimes_28',['Visual Studio Dynamic vs Static Runtimes',['../dir_df5ccadbaeaec269c116ba4c8accecee.html#autotoc_md398',1,'']]],
  ['void_20value_20not_20ignored_20as_20it_20ought_20to_20be_20what_20does_20this_20mean_29',['My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md91',1,'']]],
  ['vs_20static_20runtimes_30',['Visual Studio Dynamic vs Static Runtimes',['../dir_df5ccadbaeaec269c116ba4c8accecee.html#autotoc_md398',1,'']]],
  ['vs_20unexpected_20calls_31',['Understanding Uninteresting vs Unexpected Calls',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#uninteresting-vs-unexpected',1,'']]]
];
