var searchData=
[
  ['lambda_20as_20an_20action_0',['Using a Function, Functor, or Lambda as an Action',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md246',1,'']]],
  ['lambda_20callback_20without_20arguments_1',['Invoking a Function/Method/Functor/Lambda/Callback Without Arguments',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md153',1,'']]],
  ['lambdas_20as_20actions_2',['Using Functions/Methods/Functors/Lambdas as Actions',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#FunctionsAsActions',1,'']]],
  ['leak_20messages_20on_20windows_3',['How do I suppress the memory leak messages on Windows?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md107',1,'']]],
  ['legacy_20gmock_20faq_4',['Legacy gMock FAQ',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html',1,'']]],
  ['legacy_20macro_20based_20actions_5',['Legacy macro-based Actions',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md173',1,'']]],
  ['legacy_20macro_20based_20parameterized_20actions_6',['Legacy macro-based parameterized Actions',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md174',1,'']]],
  ['legacy_20matcher_20implementation_7',['Legacy Matcher Implementation',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md171',1,'']]],
  ['legacy_20workarounds_20for_20move_20only_20types_8',['Legacy workarounds for move-only types',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#LegacyMoveOnly',1,'']]],
  ['library_20dll_9',['As a Shared Library (DLL)',['../dir_df5ccadbaeaec269c116ba4c8accecee.html#autotoc_md402',1,'']]],
  ['library_20support_20features_10',['Underlying library support features',['../dir_2bd60d4bfa683c373d0268d1dac4c377.html#autotoc_md390',1,'']]],
  ['license_20agreements_11',['Contributor License Agreements',['../md_cmake-build-debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md1',1,'']]],
  ['like_20calling_20my_20entire_20test_20suite_20deathtest_20when_20it_20contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_12',['But I don&apos;t like calling my entire test suite *DeathTest when it contains both death tests and non-death tests. What do I do?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md104',1,'']]],
  ['limitations_13',['Known Limitations',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2primer.html#autotoc_md232',1,'']]],
  ['line_20testinfo_3a_3aline_14',['line {TestInfo::line}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md308',1,'']]],
  ['line_5fnumber_20testpartresult_3a_3aline_5fnumber_15',['line_number {TestPartResult::line_number}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md356',1,'']]],
  ['list_16',['Deprecated List',['../deprecated.html',1,'']]],
  ['listeners_17',['Listeners',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md56',1,'Defining Event Listeners'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md58',1,'Generating Failures in Listeners'],['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md57',1,'Using Event Listeners']]],
  ['listeners_20unittest_3a_3alisteners_18',['listeners {UnitTest::listeners}',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md336',1,'']]],
  ['listing_20test_20names_19',['Listing Test Names',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md61',1,'']]],
  ['live_20at_20head_20',['Live at Head',['../dir_24655302de266b7dee5d60163f030803.html#autotoc_md406',1,'']]],
  ['live_20values_20from_20mock_20methods_21',['Returning Live Values from Mock Methods',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md148',1,'']]],
  ['log_20messages_20in_20a_20death_20test_20s_20child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_22',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md105',1,'']]],
  ['log_20messages_20what_20do_20i_20do_23',['GoogleTest output is buried in a whole bunch of LOG messages. What do I do?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md98',1,'']]],
  ['log_20messages_20when_20the_20death_20test_20succeeds_24',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md105',1,'']]],
  ['logging_20additional_20information_25',['Logging Additional Information',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md42',1,'']]],
  ['logging_3a_26',['Logging:',['../dir_2bd60d4bfa683c373d0268d1dac4c377.html#autotoc_md388',1,'']]],
  ['logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_27',['I have several test suites which share the same test fixture logic, do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md97',1,'']]],
  ['lost_20after_20the_20death_20test_20finishes_20why_28',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md87',1,'']]],
  ['lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_29',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_cmake-build-debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md194',1,'']]]
];
